name: BUILD - build and binary upload

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      # Install and setup go
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # setup gopath
      - name: Set PATH
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      # checkout relayer
      - name: checkout relayer
        uses: actions/checkout@v2

      # setup cache
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # setup substrate node
      - name: install rust
        run: |
          curl https://sh.rustup.rs -sSf | sh
          source ~/.cargo/env
      - name: update rust version
        run: |
          rustup default stable && rustup update
          rustup update nightly && rustup target add wasm32-unknown-unknown --toolchain nightly
      - name: clone substrate node template
        run: git clone https://github.com/substrate-developer-hub/substrate-node-template
      - name: build substrate node template
        run: |
          cd substrate-node-template && git checkout latest
          cargo build --release
      - name: start substrate node
        run:  ./target/release/node-template --dev

      # unit tests
      - name: run unit tests
        run: make test
      # build binary
      - name: build binary and move to upload location
        run: make build

      # upload resulting binaries
      - name: upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: rly
          path: ./build/rly
